name: Check Power Daily #显示在 GitHub 网页里的名字

on:
  schedule:
    - cron: '10 16 * * *'    # 上海时间 00:10 (16点 UTC)
      timezone: Asia/Shanghai
    - cron: '15 20 * * *'    # 上海时间 04:15 (20点 UTC)
      timezone: Asia/Shanghai
    - cron: '10 1 * * *'     # 上海时间 09:10 (1点 UTC)
      timezone: Asia/Shanghai
    - cron: '10 5 * * *'     # 上海时间 13:10 (5点 UTC)
      timezone: Asia/Shanghai
    - cron: '55 1 * * *'    # 上海时间 01:20 (17点 UTC)
      timezone: Asia/Shanghai
    - cron: '55 9 * * *'    # 上海时间 01:20 (17点 UTC)
      timezone: Asia/Shanghai    
  workflow_dispatch:    # 允许你手动在网页上点击“Run workflow”来测试

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs: #有哪些任务要做
  build: #任务名字,随意起
    runs-on: ubuntu-latest #给我一台最新Ubuntu服务器,Github自动提供,相当于远程Linux电脑
    steps: #步骤,下面每个-都是一条操作
      - name: Checkout code #步骤名称
        uses: actions/checkout@v4 #把GitHub仓库下载到云服务器

      - name: Set up Python
        uses: actions/setup-python@v5 #安装Python
        with:
          python-version: '3.9' #安装Python 3.9

      - name: Install dependencies
        run: pip install -r requirements.txt #读取requirements.txt,安装里面的库

      - name: Run script
        env: #给程序提供变量
          SERVER_KEY: ${{ secrets.SERVER_KEY }} #读取GitHub Secrets里的SERVER_KEY
        run: python zidonchaxundianfei.py
